version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/java.dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: "mvn -B spring-boot:run" # -Dspring-boot.run.profiles=local"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_DEBUG: ${APP_DEBUG}
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    hostname: postgres
    volumes:
      - /tmp/epaper_pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  # wsproxy:
  #   env_file:
  #     - websocket-proxy/.env
  #   build:
  #     context: .
  #     dockerfile: ./infrastructure/docker/proxy.dockerfile
  #   depends_on:
  #     - api
  #   working_dir: /code
  #   command: "python /code/websocket-proxy.py"
  #   environment:
  #     API_URL: "http://api:8999"
  #     WS_URL: "ws://api:8999/ws"
  #   tty: true
  #   ports:
  #     - "5000:5000"
  #     - "5006:5006/udp"
